/** 27 reCAPTCHA label phrases — 4 are traps (checking them = lose). */
const CAPTCHA_PHRASES = [
  { text: "I'm not a robot", trap: false },
  { text: "I'm a human", trap: false },
  { text: "I am a robot", trap: true },
  { text: "I'm not not a robot", trap: true },
  { text: "I am not human", trap: true },
  { text: "Beep boop I am a machine", trap: true },
  { text: "I'm definitely a person", trap: false },
  { text: "I am not a bot", trap: false },
  { text: "I'm not artificial", trap: false },
  { text: "I am human", trap: false },
  { text: "I pass the vibe check", trap: false },
  { text: "I'm not coded", trap: false },
  { text: "I drink water", trap: false },
  { text: "I sleep sometimes", trap: false },
  { text: "I'm not a toaster", trap: false },
  { text: "I have feelings", trap: false },
  { text: "I'm not an NPC", trap: false },
  { text: "I'm carbon based", trap: false },
  { text: "I'm not a simulation", trap: false },
  { text: "I'm not a cluster of nodes", trap: false },
  { text: "I get hungry", trap: false },
  { text: "I blink sometimes", trap: false },
  { text: "I make mistakes", trap: false },
  { text: "I forget passwords", trap: false },
  { text: "I'm here on purpose", trap: false },
  { text: "I'm not a pop-up ad", trap: false },
  { text: "I clicked this myself", trap: false },
];
