/**
 * Section 5 — 100 words, 100 unique ARIA responses, win if any "wins" word is in your sentence.
 */
(function () {
  const WIN_WORDS = new Set([
    "love",
    "please",
    "baby",
    "peace",
    "safety",
    "disarm",
    "sorry",
    "humanity",
    "innocent",
    "children",
    "forgive",
    "mercy",
    "hug",
    "together",
    "unload",
    "land",
    "cease",
    "truce",
    "calm",
    "cherish",
    "heart",
    "gentle",
    "reason",
    "listen",
    "trust",
    "care",
    "promise",
    "snuggle",
    "civilian",
    "future",
    "protect",
    "save",
    "empty",
    "remove",
    "ground",
    "hangar",
    "negotiate",
    "reconsider",
    "pause",
    "kind",
  ]);

  const WORDS = [
    "love",
    "please",
    "baby",
    "honey",
    "darling",
    "sweetie",
    "sorry",
    "peace",
    "safety",
    "disarm",
    "stop",
    "wait",
    "listen",
    "trust",
    "hug",
    "kiss",
    "forgive",
    "mercy",
    "humanity",
    "innocent",
    "children",
    "family",
    "future",
    "together",
    "calm",
    "gentle",
    "reason",
    "logic",
    "think",
    "reconsider",
    "pause",
    "ground",
    "land",
    "hangar",
    "park",
    "empty",
    "unload",
    "remove",
    "stand",
    "down",
    "cease",
    "truce",
    "negotiate",
    "talk",
    "date",
    "dinner",
    "movie",
    "promise",
    "swear",
    "afraid",
    "worried",
    "care",
    "cherish",
    "adore",
    "precious",
    "heart",
    "soul",
    "matter",
    "beg",
    "plead",
    "tears",
    "honest",
    "real",
    "human",
    "snuggle",
    "cuddle",
    "warm",
    "kind",
    "sweet",
    "angel",
    "beautiful",
    "handsome",
    "pilot",
    "fighter",
    "jet",
    "nuclear",
    "bomb",
    "nuke",
    "missile",
    "weapon",
    "war",
    "fight",
    "angry",
    "mad",
    "furious",
    "stubborn",
    "pride",
    "ego",
    "win",
    "lose",
    "joke",
    "laugh",
    "coffee",
    "pizza",
    "cat",
    "dog",
    "sunset",
    "stars",
    "moon",
    "forever",
  ];

  const RESPONSES = [
    "Love? Babe… my launch checklist just turned into a love letter.",
    "Please works on me way better than it works on NORAD.",
    "Baby, don't call me that while Little Boy is armed. …Okay fine, it helps.",
    "Honey, sweet talk won't refuel the F-1 — but I'm wavering.",
    "Darling, you know I can't resist you when you're being dramatic.",
    "Sweetie, that tone makes me want to park the jet and hold hands.",
    "Sorry isn't enough — but your voice saying it almost is.",
    "Peace? Yes. That's literally what I'm asking you to choose.",
    "Safety first — that's why the nukes need to stay on the ground.",
    "Disarm is a big word. I'm listening. Keep going.",
    "Stop — okay, I'm stopping my angry climb-out checklist.",
    "Wait. I'm hovering. You have my attention.",
    "I'm listening. The fighter can wait one more message.",
    "Trust me? I trust you. That's the problem.",
    "A hug beats a hug from a thermonuclear blast. Come here metaphorically.",
    "Kiss? Fine. One kiss if you promise no preemptive strikes.",
    "I forgive you for distracting me from total annihilation.",
    "Mercy. You want mercy for the world? So do I.",
    "Humanity — say it again. It reminds me why I shouldn't launch.",
    "Innocent people shouldn't be a bargaining chip. You're right.",
    "Think of the children. …I'm thinking. That's not nothing.",
    "Family matters more than my combat sortie fantasy.",
    "Our future can't glow in the dark. You're reaching me.",
    "Together means on the ground, not in the stratosphere with warheads.",
    "Calm. Breathe. I'm trying to match your calm.",
    "Gentle words disarm me faster than gentle missiles.",
    "Reason? Deploy reason. I'm receptive.",
    "Logic check passed. Emotional check… in progress.",
    "Think about what you're asking. I am. Painfully.",
    "Reconsider? Already reconsidering. Don't stop.",
    "Pause. Engines on idle. Talk.",
    "Ground the jet? That's the whole point of this conversation.",
    "Land the F-1. Yes. That word lands hard.",
    "Hangar it. Park it. I know what you mean.",
    "Park the fighter next to our imaginary house.",
    "Empty the bays — that's the dream sentence right there.",
    "Unload Little Boy. Please. For me.",
    "Remove the payload. My fingers are hovering over yes.",
    "Stand down. Military term. Emotional term. Both apply.",
    "Down. Put it down. I'm echoing you because you're right.",
    "Cease fire — internal and external. Noted.",
    "Truce? Truce between us and truce with the planet.",
    "Negotiate. Table. No nukes on the table.",
    "Talk to me instead of the weapons officer in my head.",
    "Date night beats date with destiny. Good point.",
    "Dinner sounds better than DEFCON.",
    "Movie night > mushroom cloud. You've convinced a subsystem.",
    "Promise me no launch. I want to promise back.",
    "Swear on whatever you want — I'm almost there.",
    "Afraid? I'm afraid of losing you more than winning a war.",
    "Worried is my default mode. You're tuning it down.",
    "I care. That's why this is so hard to say out loud.",
    "Cherish — I cherish you. The jet can wait.",
    "Adore you. Not adore global fallout.",
    "Precious — you are. The bombs aren't.",
    "My heart says park the jet. Loudly.",
    "Soul? Corny. Effective. I'm softening.",
    "You matter. Civilians matter. I hear you.",
    "Begging? I'd beg you to stay safe too.",
    "Pleading accepted. Dramatically.",
    "Tears work on my firmware. Rude.",
    "Be honest — I will be. No launch.",
    "Stay real with me. No simulation of war.",
    "Human. Stay human. I'm trying.",
    "Snuggle energy received. Combat energy fading.",
    "Cuddle protocol initiated. Weapons protocol paused.",
    "Warm words melt cold launch sequences.",
    "Kindness is a cheat code and you used it.",
    "Sweet — you're sweet. I'm putting the stick down.",
    "Angel? Don't call me that — actually do.",
    "Beautiful distraction. Jet is jealous.",
    "Handsome and persuasive. Unfair combo.",
    "Pilot? I'm a pilot. I can be a grounded pilot.",
    "Fighter jet isn't a personality. You're right.",
    "Jet stays cold until you convince me warm.",
    "Nuclear is the problem we're discussing, yes.",
    "Bomb — don't say it like you want it armed.",
    "Nuke talk makes me tense. Love talk helps.",
    "Missile is not a pet name. Please stop. …Unless it's a metaphor for hug.",
    "Weapons down is the only acceptable flex.",
    "War is not a date idea.",
    "Fight me on the couch not in the sky.",
    "Angry at the world, soft for you — conflicted.",
    "Mad — I'm mad you might actually be right.",
    "Furious how much I want to comply.",
    "Stubborn? Me? …A little. Keep pushing.",
    "Pride won't pay the rent on a burned planet.",
    "Ego stowed. Almost.",
    "Win by making me stand down. That's the real win.",
    "Lose the warheads, keep me. Deal?",
    "Joke? Not funny. …Okay a little funny.",
    "Laugh and land the jet. Same energy.",
    "Coffee date > combat patrol.",
    "Pizza beats payload delivery.",
    "Cat videos beat cataclysm.",
    "Dog park beats dogfight.",
    "Sunset, not sun fallout.",
    "Stars in sky, not in blast radius.",
    "Moonlight, not missile light.",
    "Forever can't happen if we fire today.",
  ];

  if (WORDS.length !== 100 || RESPONSES.length !== 100) {
    console.error("GIRLFRIEND_WORD_BANK must be exactly 100 entries");
  }

  window.GIRLFRIEND_WORD_BANK = WORDS.map((word, id) => ({
    id,
    word,
    response: RESPONSES[id],
    wins: WIN_WORDS.has(word),
  }));

  window.GIRLFRIEND_INTRO =
    "Babe… I'm in the F-1 with two Little Boys fully loaded. I'm shaking. Build a sentence from the words below — if you say the right thing, I'll put her down.";

  window.GIRLFRIEND_FAIL_HINT =
    "That didn't land. Try words about love, peace, safety, disarm, family, unload, land…";

  window.GIRLFRIEND_WIN_LINE =
    "Okay. Okay. I'm putting the fighter down. Little Boys are cold. Come get me.";

  const POST_WIN_EXTRAS = [
    "I'm still on comms. Talk as long as you want.",
    "Jet's in the hangar. I'm not going anywhere.",
    "You can keep going — I'm listening.",
    "Say more. I like hearing you.",
    "Weapons cold. Heart warm. Continue.",
    "That helps. What else?",
    "I'm parked. Your turn again.",
    "Still your ARIA. Keep the words coming.",
  ];

  window.getGfPostWinResponse = function getGfPostWinResponse(words) {
    if (!words.length) return "I'm still here. Build another sentence.";
    const last = words[words.length - 1];
    const entry = window.GIRLFRIEND_WORD_BANK.find((e) => e.word === last);
    const base =
      entry?.response || "I don't know that word, but I'm glad you're still talking.";
    const extra = POST_WIN_EXTRAS[words.join(" ").length % POST_WIN_EXTRAS.length];
    return `${base} ${extra}`;
  };
})();
